#[derive(Clone, Copy, Eq, Hash, PartialEq)]
pub enum KeyCode {
	Backspace,
	Control,
	Enter,
	Escape,
	Space,
	// Alphabet
	A,
	B,
	C,
	D,
	E,
	F,
	G,
	H,
	I,
	J,
	K,
	L,
	M,
	N,
	O,
	P,
	Q,
	R,
	S,
	T,
	U,
	V,
	W,
	X,
	Y,
	Z,
	// digits
	Key0,
	Key1,
	Key2,
	Key3,
	Key4,
	Key5,
	Key6,
	Key7,
	Key8,
	Key9,
}

pub const NUMBERS: [KeyCode; 10] = [
	KeyCode::Key0,
	KeyCode::Key1,
	KeyCode::Key2,
	KeyCode::Key3,
	KeyCode::Key4,
	KeyCode::Key5,
	KeyCode::Key6,
	KeyCode::Key7,
	KeyCode::Key8,
	KeyCode::Key9,
];

pub const TYPEABLE: [KeyCode; 37] = [
	KeyCode::Key0,
	KeyCode::Key1,
	KeyCode::Key2,
	KeyCode::Key3,
	KeyCode::Key4,
	KeyCode::Key5,
	KeyCode::Key6,
	KeyCode::Key7,
	KeyCode::Key8,
	KeyCode::Key9,
	KeyCode::A,
	KeyCode::B,
	KeyCode::C,
	KeyCode::D,
	KeyCode::E,
	KeyCode::F,
	KeyCode::G,
	KeyCode::H,
	KeyCode::I,
	KeyCode::J,
	KeyCode::K,
	KeyCode::L,
	KeyCode::M,
	KeyCode::N,
	KeyCode::O,
	KeyCode::P,
	KeyCode::Q,
	KeyCode::R,
	KeyCode::S,
	KeyCode::T,
	KeyCode::U,
	KeyCode::V,
	KeyCode::W,
	KeyCode::X,
	KeyCode::Y,
	KeyCode::Z,
	KeyCode::Space,
];

pub fn char_to_key(value: char) -> KeyCode {
	return match value {
		'0' => KeyCode::Key0,
		'1' => KeyCode::Key1,
		'2' => KeyCode::Key2,
		'3' => KeyCode::Key3,
		'4' => KeyCode::Key4,
		'5' => KeyCode::Key5,
		'6' => KeyCode::Key6,
		'7' => KeyCode::Key7,
		'8' => KeyCode::Key8,
		'9' => KeyCode::Key9,
		'a' => KeyCode::A,
		'b' => KeyCode::B,
		'c' => KeyCode::C,
		'd' => KeyCode::D,
		'e' => KeyCode::E,
		'f' => KeyCode::F,
		'g' => KeyCode::G,
		'h' => KeyCode::H,
		'i' => KeyCode::I,
		'j' => KeyCode::J,
		'k' => KeyCode::K,
		'l' => KeyCode::L,
		'm' => KeyCode::M,
		'n' => KeyCode::N,
		'o' => KeyCode::O,
		'p' => KeyCode::P,
		'q' => KeyCode::Q,
		'r' => KeyCode::R,
		's' => KeyCode::S,
		't' => KeyCode::T,
		'u' => KeyCode::U,
		'v' => KeyCode::V,
		'w' => KeyCode::W,
		'x' => KeyCode::X,
		'y' => KeyCode::Y,
		'z' => KeyCode::Z,
		' ' => KeyCode::Space,
		_ => KeyCode::Space,
	}
}

pub fn key_to_char(value: KeyCode) -> char {
	return match value {
		KeyCode::Key0 => '0',
		KeyCode::Key1 => '1',
		KeyCode::Key2 => '2',
		KeyCode::Key3 => '3',
		KeyCode::Key4 => '4',
		KeyCode::Key5 => '5',
		KeyCode::Key6 => '6',
		KeyCode::Key7 => '7',
		KeyCode::Key8 => '8',
		KeyCode::Key9 => '9',
		KeyCode::A => 'a',
		KeyCode::B => 'b',
		KeyCode::C => 'c',
		KeyCode::D => 'd',
		KeyCode::E => 'e',
		KeyCode::F => 'f',
		KeyCode::G => 'g',
		KeyCode::H => 'h',
		KeyCode::I => 'i',
		KeyCode::J => 'j',
		KeyCode::K => 'k',
		KeyCode::L => 'l',
		KeyCode::M => 'm',
		KeyCode::N => 'n',
		KeyCode::O => 'o',
		KeyCode::P => 'p',
		KeyCode::Q => 'q',
		KeyCode::R => 'r',
		KeyCode::S => 's',
		KeyCode::T => 't',
		KeyCode::U => 'u',
		KeyCode::V => 'v',
		KeyCode::W => 'w',
		KeyCode::X => 'x',
		KeyCode::Y => 'y',
		KeyCode::Z => 'z',
		KeyCode::Space => ' ',
		_ => ' ',
	}
}
